@startuml
start

:initialize numbers = [4, 9, 2, 7, 6, 3, 8];
:i = 0;
:total = 0;

while (i < len(numbers)?) is (yes)
    :n = numbers[i];

    if (n == 7?) then (yes)
        break
    endif

    if (n % 2 == 0?) then (yes)
        :total = total + n;
    endif

    :i = i + 1;

endwhile (no)

:print total;

stop
@enduml