@startuml
start

:initialize numbers = [3, 8, 1, 6, 5];
:sum_even = 0;
:sum_odd = 0;

repeat
    :get next n from numbers;

    if (n % 2 == 0?) then (yes)
        :sum_even = sum_even + n;
    else (no)
        :sum_odd = sum_odd + n;
    endif

repeat while (more elements in numbers?)

:print "Even:", sum_even;
:print "Odd:", sum_odd;

stop
@enduml